### ISSUE TITLE
get_open_data_params_schema takes an unreasonable amount of time

### ISSUE THREAD

**Issue by TonioF** [dcs4cop/xcube-cmems#26]
Calling get_open_data_params_schema on the store might take for some data sets a lot of time (we observed ~ 15 minutes for cmems_obs-si_ant_phy_nrt_l3-1km_P1D ) . An investigation showed that this was because get_open_data_params_schema called describe_data, which first called open_data and then tried to create a gridmapping from the dataset.

The logic weakness here is that get_open_data_params_schema requires to open the dataset first. It should not do that. Instead, it should solely rely on the information it can get without opening the dataset. We could try to extract such information from, e.g.: https://cmems-catalog-ro.cls.fr/geonetwork/srv/eng/csw-MYOCEAN-CORE-PRODUCTS?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&ElementSetName=full&id=2ed3a04a-7dca-4eb0-b0e6-22365a3273a0 .

If we do not have any information, we may omit.

**Comment by TejasMorbagal** [comment]
@TonioF As you suggested, I will try to use csw api to extract the required information, if it takes reasonable time. Otherwise, I skip it and return open_params with None.
